[sway]
enable					= true
config_file				= "$HOME/.config/i3/config"

[sway.client]
focused.border			= "#782929"
focused.background		= "#222222"
focused.text			= "#cc6666"
focused.indicator		= "#872e2e"
focused.child_border	= "#782929"
focused_inactive.border			= "#333333"
focused_inactive.background		= "#5f676a"
focused_inactive.text			= "#ffffff"
focused_inactive.indicator		= "#484e50"
focused_inactive.child_border	= "#5f676a"
unfocused.border		= "#333333"
unfocused.background	= "#111111"
unfocused.text			= "#888888"
unfocused.indicator		= "#292d2e"
unfocused.child_border	= "#222222"
urgent.border		= "#2f343a"
urgent.background	= "#900000"
urgent.text			= "#ffffff"
urgent.indicator	= "#900000"
urgent.child_border = "#900000"
placeholder.border			= "#000000"
placeholder.background		= "#0c0c0c"
placeholder.text			= "#ffffff"
placeholder.indicator		= "#000000"
placehodler.child_border	= "#0c0c0c"
background = "#ffffff"

[waybar]
enable		= true
config_file	= "$HOME/.config/waybar/style.css"
warning		= "#A54242"
caution		= "#45475a"
performance = "#f5c2e7"
audio		= "#cba6f7"
misc		= "#94e2d5"
date		= "#a6e3a1"
work		= "#cc6666"
window		= "#cc6666"
resize		= "#eba0ac"
process		= "#fa8989"
border		= "#782929"

[rofi]
enable								= true
config_file							= "$HOME/.config/rofi/custom_themes/template.rasi"
active-foreground					= "#ff6666ff" #ff6666
selected-active-background			= "#ed4545ff" #ed4545
alternate-active-background			= "#4b5160e3" #4b5160
lightfg								= "#586875ff" #586875
lightbg								= "#eee8d5ff" #eee8d5
accent-color						= "#cc6666ff" #cc6666
border-color						= "#782929ff" #782929
